name: xeus-r-wasm-build
channels:
  - https://repo.prefix.dev/emscripten-forge-4x
  - conda-forge
dependencies:
  # Xeus-R
  - cmake
  - pkg-config
  - emscripten_emscripten-wasm32
  # Hera
  - r-base
  - r-rlang
  - r-jsonlite
  - r-base64enc
  - r-digest
  - r-fastmap
  - r-htmltools
  - r-cli
  - r-glue
  - r-vctrs
  - r-evaluate
  - r-irdisplay
  - r-r6
  - r-repr
  # JupyterLite
  - jupyter_server
  - jupyterlite-core
  - jupyterlite-xeus
