name: xeus-r
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  - cxx-compiler
  - ninja
  # Host dependencies
  - xeus>=6.0.0,<7
  - xeus-zmq>=4.0,<5.0
  - nlohmann_json
  - r-base >=4
  # Run dependencies
  - r-cli
  - r-evaluate
  - r-glue
  - r-IRdisplay
  - r-jsonlite
  - r-r6
  - r-repr
  - r-rlang
  # Test dependencies
  - pytest
  - jupyter_kernel_test<0.8
  - nbval
  - pytest-rerunfailures
  - r-ggplot2
  - r-htmltools
